FROM maven:3.9-eclipse-temurin-21-alpine
WORKDIR /app

COPY pom.xml ./
RUN mvn dependency:go-offline

COPY src ./src
RUN mvn package -DskipTests

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "target/{{artifactId}}-0.0.1-SNAPSHOT.jar"]
